import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
const root = await mkdtemp(join(tmpdir(), "ak-policy-"));
process.env.AGENT_DATA_DIR = root;
process.env.HOME = root;
process.env.SITES = JSON.stringify([{ id: "test", repo: "https://example.com/test.git", branch: "main", domain: "test.example" }]);
const { prepareConversation, conversationIdFor, sessionIdFor, rotateConversation } = await import("../claude.js");
const { defaultHarness, writeLastUsage, loadHarness, fallbackHarness } = await import("../harness.js");
const { checkoutPath } = await import("../checkouts.js");
const { rotationReason } = await import("../session-policy.js");
const harness = defaultHarness();
async function seed(tokens: number, minutes: number, freshCron = false) {
  const id = await conversationIdFor("test", "page");
  await writeLastUsage("test", { contextTokens: tokens, contextPct: 0, at: new Date(Date.now() - minutes * 60000).toISOString(), conversationId: id, freshCron }, "page");
  const path = join(root, ".claude/projects", checkoutPath("test").replace(/[/.]/g, "-"), `${sessionIdFor(id)}.jsonl`);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, Array.from({ length: 10 }, (_, i) => JSON.stringify({ type: i % 2 ? "assistant" : "user", message: { content: [{ type: "text", text: `message-${i} ` + "x".repeat(800) }] } })).join("\n"));
  return id;
}
let old = await seed(150001, 0);
let next = await prepareConversation("test", "page", harness);
assert.notEqual(next.conversationId, old);
assert.ok(next.handoff.startsWith("Earlier in this chat (for context)"));
assert.ok(!next.handoff.includes("message-3"));
assert.ok(next.handoff.includes("message-4"));
assert.ok(next.handoff.length < 3200);
assert.equal(next.lastUsage, null);
old = await seed(60001, 61);
assert.notEqual((await prepareConversation("test", "page", harness)).conversationId, old);
old = await seed(60000, 61);
assert.equal((await prepareConversation("test", "page", harness)).conversationId, old);
old = await seed(10000, 0, true);
assert.equal((await prepareConversation("test", "page", harness)).conversationId, old, "recent fresh cron unchanged");
await seed(10000, 61, true);
assert.notEqual((await prepareConversation("test", "page", harness)).conversationId, old, "idle fresh cron detached even if small");
await seed(800000, 90);
const fresh = await rotateConversation("test", "page");
assert.equal((await prepareConversation("test", "page", harness)).conversationId, fresh, "fresh cron/manual rotation ignores old usage");
assert.equal((await prepareConversation("test", "other", harness)).handoff, "", "page isolation");
old = await seed(1000, 0);
next = await prepareConversation("test", "page", harness, "redeploy continuation");
assert.notEqual(next.conversationId, old);
assert.ok(next.handoff.includes("message-9"));
assert.equal(rotationReason({ contextTokens: 150000, contextPct: 0, at: new Date().toISOString() }, {}), null);
const settings = join(root, "agent-keyboard/sites/test/settings.json");
await writeFile(settings, JSON.stringify({ maxContextTokens: 90000, maxBudgetUsd: 1.5, pages: { "/page": { maxContextTokens: 70000, turnMaxContextTokens: -1, idleRotateMinutes: "1", idleRotateMinTokens: 1000, maxBudgetUsd: 2 } } }));
const h = await loadHarness("test", "page");
assert.equal(h.settings.maxContextTokens, 70000);
assert.equal(h.settings.maxBudgetUsd, 2);
assert.equal(h.settings.idleRotateMinTokens, 1000);
assert.equal(h.warnings.length, 2);
assert.equal(fallbackHarness(h.settings).settings.maxContextTokens, 70000);
console.log("session-policy-check OK");
